openapi: 3.0.2
info: 
paths: 

components:
  schemas:
    GuildBattleEventRes:
      type: object
      properties:
        is_entry:
          type: boolean
          description: エントリー状況
        event:
          $ref: ./event.yaml#/components/schemas/EventDetails
        characters:
          $ref: ./character.yaml#/components/schemas/UserCharacterDetails
          description: ギルド全体で登録されているキャラクターs
      required:
        - is_entry
        - event
        - characters
    
    GuildBattleEntryCharacterReq:
      type: object
      properties:
        items:
          type: array
          items: 
            $ref: ../utils/default.yaml#/components/schemas/Id
          description: > 
            空の時は全て外す
      required:
        - items

    GuildBattleEventSummeryResultsRes:
      type: object
      properties:
        items:
          type: array
          items: 
            $ref: ./guild_battle.yaml#/components/schemas/GuildBattleResultSummery
        pager:
          $ref: ../utils/pager.yaml#/components/schemas/Pager
      required:
        - items
        - pager
    
    GuildBattleEventResultRes:
      type: object
      properties:
        item:
          $ref: ./guild_battle.yaml#/components/schemas/GuildBattleResult
      required:
        - item
    
    GuildBattleEventMattingsRes:
      type: object
      properties:
        items:
          type: array
          items: 
            $ref: ./guild_battle.yaml#/components/schemas/GuildBattleEventMattingSummery
      required:
        - items
    
    GuildBattleEventMattingDetailRes:
      type: object
      properties:
        item:
          $ref: ./guild_battle.yaml#/components/schemas/GuildBattleResult
      required:
        - item

    GuildBattleEvent:
      type: object
      properties:
        id:
          $ref: ../utils/default.yaml#/components/schemas/Id
        event:
          $ref: ./event.yaml#/components/schemas/EventDetails
      required:
        - id
        - event

    GuildBattleResult:
      type: object
      properties:
        win_guild:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
        lose_guild:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
        event:
          $ref: ./event.yaml#/components/schemas/EventDetails
      required:
        - win_guild
        - lose_guild
        - event
    
    GuildBattleResultSummery:
      type: object
      properties:
        win_guild_summery:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
        lose_guild_summery:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
        event_summery:
          $ref: ./event.yaml#/components/schemas/EventSummery
      required:
        - win_guild_summery
        - lose_guild_summery
        - event_summery

    GuildBattleEventMattingDetails:
      type: object
      properties:
        guild_a:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
        guild_b:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
      required:
        - guild_a
        - guild_b

    GuildBattleEventMattingSummery:
      type: object
      properties:
        guild_a:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
        guild_b:
          $ref: ./guild.yaml#/components/schemas/GuildSummery
      required:
        - guild_a
        - guild_b
    