openapi: 3.0.2
info: 
paths: 

components:
  schemas:
    GetGuildFundRes:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: ../utils/default.yaml#/components/schemas/Resource
      required:
        - items

    GetGuildFundLogsRes:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: ./guild_fund.yaml#/components/schemas/GuildFundLog
        pager:
          $ref: ../utils/pager.yaml#/components/schemas/Pager
      required:
        - items
        - pager

    GetGuildFundLogDetailsRes:
      type: object
      properties:
        guild:
          $ref: ./guild_fund.yaml#/components/schemas/GuildFundLog
      required:
        - guild


    GuildFundLog:
      type: object
      properties:
        id:
          $ref: ../utils/default.yaml#/components/schemas/Id
        user_name: 
          type: string
          description: ユーザー名
          example: 山田 太郎
        money:
          $ref: ../utils/default.yaml#/components/schemas/Resource
        fund_log_type:
          type: integer
          enum:
            - 1 # 支出(支払い時)
            - 2 # 収入(出資時)
            - 3 # 報酬(ギルド抗争報酬)
            - 4 # 徴税(?する?)
        receipt:
          type: string
          description: 利用目的を返却 
          example: >
            {item名}を{fund_log_type(1, 支出)}購入
            {報酬名}を{fund_log_type(3, 報酬)}受け取り
        execute_at:
          $ref: ../utils/default.yaml#/components/schemas/ExecuteAt
          description: 作成日時
      required:
        - id
        - user_name
        - money
        - fund_log_type
        - receipt
        - execute_at
