package: api                # 生成されるGoパッケージ名
generate:
  models: true              # モデルコードの生成
  gin-server: true          # Gin用サーバーコードの生成（echoやchiも指定可能）
  client: true              # クライアントコードの生成
  embedded-spec: true       # OpenAPI仕様をGoコードに埋め込む
output: api/api.gen.go      # 出力先ファイル
